# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pytube import YouTube 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.address_film = QtWidgets.QLineEdit(self.widget)
        self.address_film.setGeometry(QtCore.QRect(140, 110, 341, 31))
        self.address_film.setObjectName("address_film")
        self.Download = QtWidgets.QPushButton(self.widget)
        self.Download.setGeometry(QtCore.QRect(260, 270, 75, 23))
        self.Download.setObjectName("Download")
        self.address_save = QtWidgets.QLineEdit(self.widget)
        self.address_save.setGeometry(QtCore.QRect(140, 180, 341, 31))
        self.address_save.setObjectName("address_save")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 110, 101, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 101, 20))
        self.label_2.setObjectName("label_2")
        self.message = QtWidgets.QLabel(self.widget)
        self.message.setGeometry(QtCore.QRect(80, 40, 471, 31))
        self.message.setObjectName("message")
        self.Select_Resolution = QtWidgets.QComboBox(self.widget)
        self.Select_Resolution.setGeometry(QtCore.QRect(510, 110, 69, 22))
        self.Select_Resolution.setObjectName("Select_Resolution")
        self.Select_Resolution.addItem("")
        self.Select_Resolution.addItem("")
        self.Select_Resolution.addItem("")
        self.Select_Resolution.addItem("")
        self.Select_Resolution.addItem("")
        self.Select_Resolution.addItem("")
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.Download.clicked.connect(self.Youtube_Downloader)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Download.setText(_translate("MainWindow", "Download"))
        self.label.setText(_translate("MainWindow", "Youtube Address"))
        self.label_2.setText(_translate("MainWindow", "File Path Address"))
        self.message.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Select_Resolution.setItemText(0, _translate("MainWindow", "1080p"))
        self.Select_Resolution.setItemText(1, _translate("MainWindow", "720p"))
        self.Select_Resolution.setItemText(2, _translate("MainWindow", "480p"))
        self.Select_Resolution.setItemText(3, _translate("MainWindow", "360p"))
        self.Select_Resolution.setItemText(4, _translate("MainWindow", "240p"))
        self.Select_Resolution.setItemText(5, _translate("MainWindow", "144p"))

    def Youtube_Downloader(self):
        self.message.setText("")
        SAVE_PATH = self.address_save.text()

        Link= self.address_film.text()
        res=self.Select_Resolution.currentText()
        try: 
            YouTube(str(Link)).streams.filter(res=res).first().download(SAVE_PATH)
            self.message.setText("Task Completed!")
        except: 
            
            #to handle exception 
            self.message.setText("Connection Error")

        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
